name: backend_check

on:
  workflow_dispatch:
  push:
    paths:
      - common/**
      - backend/**
      - Cargo.toml
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Install local toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
          target: x86_64-unknown-linux-gnu

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Lint
        run: |
          cargo fmt -p common -p backend -- --check
          cargo clippy -p common -p backend -- -D warnings

      - name: Test
        run: |
          cargo check -p common -p backend
          cargo test -p common -p backend

      - name: Build
        working-directory: ./backend
        run: |
          cargo build --release
